version: "3"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/code
    command: >
      bash -c "python bin/init.py &&
               honcho -d . -f /Procfile start"
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    container_name: hello_postgres
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=hello
    expose:
      - 5432
